/**
 * Live Asset R2 Worker
 * Handles file upload/download/delete for Spine assets stored in Cloudflare R2.
 * Auth: HMAC-SHA256 signed tokens generated by Next.js API routes.
 */

interface Env {
  ASSETS_BUCKET: R2Bucket;
  WORKER_SECRET: string;
}

interface TokenPayload {
  sub: string;
  charId?: number;
  filename?: string;
  path?: string;
  action: 'upload' | 'download' | 'delete';
  exp: number;
}

async function verifyToken(token: string, secret: string): Promise<TokenPayload | null> {
  const parts = token.split('.');
  if (parts.length !== 2) return null;

  const [dataB64, sig] = parts;
  const data = atob(dataB64.replace(/-/g, '+').replace(/_/g, '/'));

  // Verify HMAC
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const expected = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data));
  const expectedHex = Array.from(new Uint8Array(expected))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');

  if (expectedHex !== sig) return null;

  const payload: TokenPayload = JSON.parse(data);

  // Check expiry
  if (payload.exp < Math.floor(Date.now() / 1000)) return null;

  return payload;
}

function corsHeaders(): HeadersInit {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, PUT, DELETE, OPTIONS',
    'Access-Control-Allow-Headers': 'Authorization, Content-Type',
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: corsHeaders() });
    }

    const url = new URL(request.url);
    const path = url.pathname;

    try {
      // PUT /upload/:userId/:charId/:filename
      if (request.method === 'PUT' && path.startsWith('/upload/')) {
        const authHeader = request.headers.get('Authorization');
        if (!authHeader?.startsWith('Bearer ')) {
          return new Response('Unauthorized', { status: 401, headers: corsHeaders() });
        }

        const token = authHeader.slice(7);
        const payload = await verifyToken(token, env.WORKER_SECRET);
        if (!payload || payload.action !== 'upload') {
          return new Response('Invalid token', { status: 403, headers: corsHeaders() });
        }

        const parts = path.replace('/upload/', '').split('/');
        if (parts.length < 3) {
          return new Response('Invalid path', { status: 400, headers: corsHeaders() });
        }

        const key = parts.join('/'); // userId/charId/filename
        const body = await request.arrayBuffer();
        const contentType = request.headers.get('Content-Type') || 'application/octet-stream';

        await env.ASSETS_BUCKET.put(key, body, {
          httpMetadata: { contentType },
        });

        return new Response(JSON.stringify({ key }), {
          status: 200,
          headers: { ...corsHeaders(), 'Content-Type': 'application/json' },
        });
      }

      // GET /download/:path?token=...
      if (request.method === 'GET' && path.startsWith('/download/')) {
        const token = url.searchParams.get('token');
        if (!token) {
          return new Response('Missing token', { status: 401, headers: corsHeaders() });
        }

        const payload = await verifyToken(token, env.WORKER_SECRET);
        if (!payload || payload.action !== 'download') {
          return new Response('Invalid token', { status: 403, headers: corsHeaders() });
        }

        const key = decodeURIComponent(path.replace('/download/', ''));
        if (payload.path && payload.path !== key) {
          return new Response('Path mismatch', { status: 403, headers: corsHeaders() });
        }
        const object = await env.ASSETS_BUCKET.get(key);

        if (!object) {
          return new Response('Not found', { status: 404, headers: corsHeaders() });
        }

        const headers: HeadersInit = {
          ...corsHeaders(),
          'Content-Type': object.httpMetadata?.contentType || 'application/octet-stream',
          'Cache-Control': 'public, max-age=3600',
        };

        return new Response(object.body, { status: 200, headers });
      }

      // DELETE /delete/:userId/:charId
      if (request.method === 'DELETE' && path.startsWith('/delete/')) {
        const authHeader = request.headers.get('Authorization');
        if (!authHeader?.startsWith('Bearer ')) {
          return new Response('Unauthorized', { status: 401, headers: corsHeaders() });
        }

        const token = authHeader.slice(7);
        const payload = await verifyToken(token, env.WORKER_SECRET);
        if (!payload || payload.action !== 'delete') {
          return new Response('Invalid token', { status: 403, headers: corsHeaders() });
        }

        const prefix = path.replace('/delete/', '');
        const listed = await env.ASSETS_BUCKET.list({ prefix });

        for (const obj of listed.objects) {
          await env.ASSETS_BUCKET.delete(obj.key);
        }

        return new Response(JSON.stringify({ deleted: listed.objects.length }), {
          status: 200,
          headers: { ...corsHeaders(), 'Content-Type': 'application/json' },
        });
      }

      return new Response('Not found', { status: 404, headers: corsHeaders() });
    } catch (err) {
      return new Response(`Error: ${(err as Error).message}`, {
        status: 500,
        headers: corsHeaders(),
      });
    }
  },
};
